version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/testServer
hooks:
  BeforeInstall:
    - location: /bin/hook-beforeInstall.sh
      runas: ubuntu
  AfterInstall:
    - location: /bin/hook-afterInstall.sh
      runas: ubuntu
