version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/testServer
hooks:
  AfterInstall:
    - location: /bin/hook-setup.sh
      runas: sudo
  ApplicationStart:
    - location: /bin/hook-afterinstall.sh
      runas: sudo
