version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/testServer
hooks:
  Install:
    - location: /bin/hook-setup.sh
      runas: ubuntu
  ApplicationStart:
    - location: /bin/hook-afterinstall.sh
      runas: ubuntu
